### ISSUE TITLE
Cannot create a new user.

### ISSUE THREAD

**Issue by ghost** [24coder/Hotel-Management-System#8]
Superuser works but the `manage.py flush` takes away most things.

The user registration form always throws an "invalid ID" annotation.

**Comment by anisbhsl** [comment]
@VentGrey can you present your error logs please?

**Comment by ghost** [comment]
Doesn't throw an error log, no matter which ID number is chosen when registering a new user the same bulletpoint appears.
![image](https://user-images.githubusercontent.com/24773698/60690003-59741a00-9e89-11e9-871e-4b3f7dcff05c.png)

**Comment by anisbhsl** [comment]
@VentGrey The user has to be created via admin interface. The userID is then provided to the employee and he/she has to to signup by providing his personal informations. At the time you were trying to register user, there might not be the user with that ID added from admin.
